---
# tasks file for post-install
- name: Install NTP(chrony) server on Centos
  yum:
    update_cache: yes
    name: "{{item}}"
    state: present
  when: ansible_distribution == "CentOS"
  loop:
    - chrony
    - git
    - unzip
    - wget
    - zip

- name: Starting NTP(chronyd) service on Centos
  service:
    name: chronyd
    state: started
    enabled: yes
  when: ansible_distribution == "CentOS"

- name: Install NTP server on Ubuntu
  apt:
    update_cache: yes
    name: "{{item}}"
    state: present
  when: ansible_distribution == "Ubuntu"
  loop:
    - ntp
    - git
    - unzip
    - wget
    - zip

- name: Starting NTP service on Ubuntu
  service:
    name: ntp
    state: started
    enabled: yes
  when: ansible_distribution == "Ubuntu"

- name: Banner file
  copy:
    content: '# This server is managed by ansible. No manual changes please.'
    dest: /etc/motd

- name: Deploy ntp agent conf on centos
  template:
    src: ntpconf_centos.j2 # we dont need to mention the template folder infront of the file(templates/ntpconf_centos), template will search for the file in roles/post-install/templates. As a standard, end templates file with .j2
    dest: /etc/chrony.conf
    backup: yes #to create a backup of the chrony.conf since the task will overwrite the original file
  when: ansible_distribution == "CentOS"
  notify: # to notify the handler to run the task to restart the ntp service once the task causes a change.
    - Restarting NTP(chronyd) service on Centos # this name should be exactly the same as that of the task to be executed.

- name: Deploy ntp agent conf on ubuntu
  template:
    src: ntp.conf_ubuntu.j2
    dest: /etc/ntp.conf
    backup: yes #to create a backup of the chrony.conf since the task will overwrite the original file
  when: ansible_distribution == "Ubuntu"
  notify: # to notify the handler to run the task to restart the ntp service once the task causes a change.
    - Restarting NTP service on Ubuntu # this name should be exactly the same as that of the task to be executed.

- name: Copy file
  copy:
    src: file.txt # just as how template will search for files in the roles/post-install/templates, file also has the same behaviour so remove files/ begining the filename.
    dest: /tmp/myfile.txt
