all:
  hosts: 
    web01: 
      ansible_host: 172.31.76.160 #use private ip
      ansible_user: ec2-user #the user of the host web01 machine
      ansible_ssh_private_key_file: client.pem #key must be in the current directory
    web02: 
      ansible_host: 172.31.73.29 #use private ip
      ansible_user: ec2-user #the user of the host web01 machine
      ansible_ssh_private_key_file: client.pem #key must be in the current directory
    web03: 
      ansible_host: 172.31.67.154 #use private ip
      ansible_user: ubuntu #the user of the host web01 machine
      ansible_ssh_private_key_file: client.pem #key must be in the current directory
    db01: 
      ansible_host: 172.31.73.232 #use private ip
      ansible_user: ec2-user #the user of the host web01 machine
      ansible_ssh_private_key_file: client.pem #key must be in the current directory
  children:
    webservers: 
      hosts: 
        web01:
        web02:
        web03:
    dbservers: 
      hosts:
        db01:
    group_of_groups:
      children:
        webservers:
        dbservers:
    
